baseURL = 'https://hangliuc.github.io/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„ SRE è¿›åŒ–ä¹‹è·¯'
theme = 'PaperMod'

[params]
  defaultTheme = "auto" # è·Ÿéšç³»ç»Ÿè‡ªåŠ¨åˆ‡æ¢æ·±è‰²/æµ…è‰²æ¨¡å¼
  ShowReadingTime = true # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowShareButtons = false # æš‚æ—¶å…³æ‰åˆ†äº«æŒ‰é’®
  
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ SRE çŸ¥è¯†åº“ï¼Œè¿™é‡Œè®°å½• K8s, Go å’Œä¸€åˆ‡æœ‰è¶£çš„æŠ€æœ¯ã€‚"

  [[menu.main]]
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "æœç´¢"
    url = "/search/"
    weight = 2